version: '3.3'
services:
  svg2png:
    build: .
    ports:
      - "8544:8544"
    environment:
      - SVG2PNG_HOSTS=chrome0,chrome1,chrome2,chrome3
      - SVG2PNG_TIMEOUT=30
  chrome0:
    image: yukinying/chrome-headless-browser:74.0.3729.6
    command: --no-sandbox --disable-gpu
    expose:
      - "9222"
  chrome1:
    image: yukinying/chrome-headless-browser:74.0.3729.6
    command: --no-sandbox --disable-gpu
    expose:
      - "9222"
  chrome2:
    image: yukinying/chrome-headless-browser:74.0.3729.6
    command: --no-sandbox --disable-gpu
    expose:
      - "9222"
  chrome3:
    image: yukinying/chrome-headless-browser:74.0.3729.6
    command: --no-sandbox --disable-gpu --remote-debugging-address=0.0.0.0
    expose:
      - "9222"
#  bash:
#    image: debian
#    entrypoint: /bin/sleep 10000
